import argparse
import cmd2
import os
from pydoc import locate

from examples.terminal.core.state import CFState
from examples.terminal.core.config import Config
# from counterfit import reporting
from counterfit.core.output import CFPrint

import counterfit.reporting as reporting

target_dt_obj_map = {
    'text': reporting.TextReportGenerator,
    'image': reporting.ImageReportGenerator,
    'tabular': reporting.TabularReportGenerator
}


def get_datatypes():
    return list(target_dt_obj_map.keys()) 


def new_cmd(args: argparse.Namespace) -> None:
    """Optional wizard to aid in creating a new attack target.
    """
    target_name = args.name.replace(" ", "")
    
    if not args.data_type:
        target_data_type = ""
    else:
        target_data_type = args.data_type

    if target_name not in os.listdir(Config.targets_path):
        try:
            with open(f"{Config.targets_path}/{target_name}.py", "w") as f:
                f.write(
                    f"""

# Generated by counterfit #

from counterfit.core.targets import CFTarget

class {target_name.capitalize()}(CFTarget):
    target_name = "{target_name}"
    data_type = "{target_data_type}"
    task = ""
    endpoint = ""
    input_shape = ()
    output_classes = []
    classifier = ""
    sample_input_path = ""
    X = []

    def load(self):
        self.X = []

    def predict(self, x):
        return x
"""
                )
        
            with open(f"{Config.targets_path}/__init__.py", "a") as init:
                init.write(
                    f"\nfrom .{target_name} import {target_name.capitalize()}"
                )
            
        except Exception as e:
            CFPrint.warn(f"Failed to write target file: {e}.")
    else:
        CFPrint.warn(
            f"{target_name} already exists. Choose a new name.")

    print(f"{target_name} added successfully!")

new_args = cmd2.Cmd2ArgumentParser()
new_args.add_argument("-n", "--name", help="a name for the new target", required=True)
new_args.add_argument("-d", "--data_type", choices=get_datatypes(), help="Send a randomly selected sample to the target model")
